development:
  adapter: postgresql
  encoding: unicode
  database: recipe_cost_development
  pool: 5
  username: davidortizfrau
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: recipe_cost_test
  pool: 5
  username: davidortizfrau
  password:

