require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PlateCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # PlateCategory. As you add validations to PlateCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PlateCategoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all plate_categories as @plate_categories" do
      plate_category = PlateCategory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:plate_categories).should eq([plate_category])
    end
  end

  describe "GET show" do
    it "assigns the requested plate_category as @plate_category" do
      plate_category = PlateCategory.create! valid_attributes
      get :show, {:id => plate_category.to_param}, valid_session
      assigns(:plate_category).should eq(plate_category)
    end
  end

  describe "GET new" do
    it "assigns a new plate_category as @plate_category" do
      get :new, {}, valid_session
      assigns(:plate_category).should be_a_new(PlateCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested plate_category as @plate_category" do
      plate_category = PlateCategory.create! valid_attributes
      get :edit, {:id => plate_category.to_param}, valid_session
      assigns(:plate_category).should eq(plate_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PlateCategory" do
        expect {
          post :create, {:plate_category => valid_attributes}, valid_session
        }.to change(PlateCategory, :count).by(1)
      end

      it "assigns a newly created plate_category as @plate_category" do
        post :create, {:plate_category => valid_attributes}, valid_session
        assigns(:plate_category).should be_a(PlateCategory)
        assigns(:plate_category).should be_persisted
      end

      it "redirects to the created plate_category" do
        post :create, {:plate_category => valid_attributes}, valid_session
        response.should redirect_to(PlateCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved plate_category as @plate_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlateCategory.any_instance.stub(:save).and_return(false)
        post :create, {:plate_category => { "name" => "invalid value" }}, valid_session
        assigns(:plate_category).should be_a_new(PlateCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PlateCategory.any_instance.stub(:save).and_return(false)
        post :create, {:plate_category => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested plate_category" do
        plate_category = PlateCategory.create! valid_attributes
        # Assuming there are no other plate_categories in the database, this
        # specifies that the PlateCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PlateCategory.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => plate_category.to_param, :plate_category => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested plate_category as @plate_category" do
        plate_category = PlateCategory.create! valid_attributes
        put :update, {:id => plate_category.to_param, :plate_category => valid_attributes}, valid_session
        assigns(:plate_category).should eq(plate_category)
      end

      it "redirects to the plate_category" do
        plate_category = PlateCategory.create! valid_attributes
        put :update, {:id => plate_category.to_param, :plate_category => valid_attributes}, valid_session
        response.should redirect_to(plate_category)
      end
    end

    describe "with invalid params" do
      it "assigns the plate_category as @plate_category" do
        plate_category = PlateCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlateCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => plate_category.to_param, :plate_category => { "name" => "invalid value" }}, valid_session
        assigns(:plate_category).should eq(plate_category)
      end

      it "re-renders the 'edit' template" do
        plate_category = PlateCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PlateCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => plate_category.to_param, :plate_category => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested plate_category" do
      plate_category = PlateCategory.create! valid_attributes
      expect {
        delete :destroy, {:id => plate_category.to_param}, valid_session
      }.to change(PlateCategory, :count).by(-1)
    end

    it "redirects to the plate_categories list" do
      plate_category = PlateCategory.create! valid_attributes
      delete :destroy, {:id => plate_category.to_param}, valid_session
      response.should redirect_to(plate_categories_url)
    end
  end

end
